version: '3.7'
services:
  dev:
    image: node:latest
    volumes:
      - .:/mystbot
      - /mystbot/node_modules
    working_dir: /mystbot
    command: bash -c "npm install && npm run watch"
    ports:
      - 8000:8080