version: '3.7'
services:
  install:
    image: node:latest
    working_dir: /mystbot
    volumes:
      - .:/mystbot
      # .dockerignore is not applied to volumes - the following are "ignored":
      - /mystbot/node_modules
      - /mystbot/.git
    command: npm install