version: '3.7'
services:
  dev:
    image: node:latest
    volumes:
      - .:/mystbot
      # .dockerignore is not applied to volumes - the following are "ignored":
      - /mystbot/node_modules
      - /mystbot/.git
    working_dir: /mystbot
    command: bash -c "npm install && npm run watch"