version: '3.7'
services:
  dev:
    image: node:latest
    working_dir: /mystbot
    volumes:
      - nodemodules:/mystbot/node_modules
      - .:/mystbot
      # .dockerignore is not applied to volumes - the following are "ignored":
      - /mystbot/.git
    command: npm run watch
volumes:
  nodemodules:
    external: true